<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fix existing products with correct prices and add all missing products
        $products = [
            // ELEKTRONIK CATEGORY (ID: 1) - 20 products
            [
                'name' => 'Smartphone Samsung Galaxy',
                'slug' => 'smartphone-samsung-galaxy',
                'description' => 'Smartphone flagship terbaru dari Samsung dengan layar AMOLED 6.7 inci dan kamera 108MP',
                'category_id' => 1,
                'price' => 3000000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'iPhone 15 Pro',
                'slug' => 'iphone-15-pro',
                'description' => 'iPhone terbaru dengan chip A17 Pro dan sistem kamera profesional',
                'category_id' => 1,
                'price' => 25000000,
                'stock' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Xiaomi Redmi Note 13',
                'slug' => 'xiaomi-redmi-note-13',
                'description' => 'Smartphone mid-range dengan kamera 108MP dan baterai 5000mAh',
                'category_id' => 1,
                'price' => 3500000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Laptop ASUS VivoBook',
                'slug' => 'laptop-asus-vivobook',
                'description' => 'Laptop tipis dengan processor Intel Core i5 dan RAM 8GB',
                'category_id' => 1,
                'price' => 8500000,
                'stock' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Samsung TV 55 Inch 4K',
                'slug' => 'samsung-tv-55-inch-4k',
                'description' => 'Smart TV 4K Ultra HD dengan HDR dan Smart TV features',
                'category_id' => 1,
                'price' => 7500000,
                'stock' => 6,
                'status' => 'published',
            ],
            [
                'name' => 'Sony WH-1000XM5 Headphones',
                'slug' => 'sony-wh-1000xm5-headphones',
                'description' => 'Wireless noise cancelling headphones dengan kualitas audio premium',
                'category_id' => 1,
                'price' => 4500000,
                'stock' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'iPad Air',
                'slug' => 'ipad-air',
                'description' => 'Tablet Apple dengan chip M1 dan layar 10.9 inci',
                'category_id' => 1,
                'price' => 12000000,
                'stock' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'slug' => 'nintendo-switch-oled',
                'description' => 'Console gaming hybrid dengan layar OLED 7 inci',
                'category_id' => 1,
                'price' => 5500000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Canon EOS R50 Camera',
                'slug' => 'canon-eos-r50-camera',
                'description' => 'Mirrorless camera untuk pemula dengan autofocus canggih',
                'category_id' => 1,
                'price' => 9500000,
                'stock' => 5,
                'status' => 'published',
            ],
            [
                'name' => 'Powerbank Xiaomi 20000mAh',
                'slug' => 'powerbank-xiaomi-20000mah',
                'description' => 'Powerbank high capacity dengan fast charging support',
                'category_id' => 1,
                'price' => 350000,
                'stock' => 25,
                'status' => 'published',
            ],
            [
                'name' => 'Smartwatch Apple Watch Series 9',
                'slug' => 'smartwatch-apple-watch-series-9',
                'description' => 'Smartwatch premium dengan health monitoring canggih',
                'category_id' => 1,
                'price' => 6500000,
                'stock' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'Speaker JBL Flip 6',
                'slug' => 'speaker-jbl-flip-6',
                'description' => 'Portable Bluetooth speaker dengan waterproof dan bass powerful',
                'category_id' => 1,
                'price' => 1500000,
                'stock' => 18,
                'status' => 'published',
            ],
            [
                'name' => 'USB Flash Drive SanDisk 128GB',
                'slug' => 'usb-flash-drive-sandisk-128gb',
                'description' => 'USB 3.0 flash drive dengan kecepatan transfer tinggi',
                'category_id' => 1,
                'price' => 150000,
                'stock' => 30,
                'status' => 'published',
            ],
            [
                'name' => 'Webcam Logitech C920',
                'slug' => 'webcam-logitech-c920',
                'description' => 'HD webcam untuk video conferencing dan streaming',
                'category_id' => 1,
                'price' => 1200000,
                'stock' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Mouse Wireless Logitech MX Master',
                'slug' => 'mouse-wireless-logitech-mx-master',
                'description' => 'Ergonomic wireless mouse untuk produktivitas',
                'category_id' => 1,
                'price' => 1800000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Keyboard Mechanical Keychron K2',
                'slug' => 'keyboard-mechanical-keychron-k2',
                'description' => 'Wireless mechanical keyboard dengan RGB backlight',
                'category_id' => 1,
                'price' => 2200000,
                'stock' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'Monitor LG 27 Inch 144Hz',
                'slug' => 'monitor-lg-27-inch-144hz',
                'description' => 'Gaming monitor dengan refresh rate tinggi dan response time 1ms',
                'category_id' => 1,
                'price' => 4500000,
                'stock' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Tablet Samsung Galaxy Tab S9',
                'slug' => 'tablet-samsung-galaxy-tab-s9',
                'description' => 'Premium Android tablet dengan S Pen dan layar AMOLED',
                'category_id' => 1,
                'price' => 10500000,
                'stock' => 6,
                'status' => 'published',
            ],
            [
                'name' => 'GoPro Hero 12 Black',
                'slug' => 'gopro-hero-12-black',
                'description' => 'Action camera 5.3K dengan HyperSmooth stabilization',
                'category_id' => 1,
                'price' => 7500000,
                'stock' => 8,
                'status' => 'published',
            ],

            // PAKAIAN CATEGORY (ID: 2) - 18 products
            [
                'name' => 'Kaos Polos Hitam',
                'slug' => 'kaos-polos-hitam',
                'description' => 'Kaos katun 100% combed 30s, nyaman dipakai sehari-hari',
                'category_id' => 2,
                'price' => 50000,
                'stock' => 50,
                'status' => 'published',
            ],
            [
                'name' => 'Baju Kuning 22',
                'slug' => 'baju-kuning-22',
                'description' => 'Kaos berwarna kuning terang dengan desain modern',
                'category_id' => 2,
                'price' => 20000,
                'stock' => 30,
                'status' => 'published',
            ],
            [
                'name' => 'Baju Kuning',
                'slug' => 'baju-kuning',
                'description' => 'Kaos kuning dengan bahan katun pilihan',
                'category_id' => 2,
                'price' => 15000,
                'stock' => 25,
                'status' => 'published',
            ],
            [
                'name' => 'Kemeja Putih Formal',
                'slug' => 'kemeja-putih-formal',
                'description' => 'Kemeja katun formal untuk kerja dan acara resmi',
                'category_id' => 2,
                'price' => 150000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Celana Jeans Denim',
                'slug' => 'celana-jeans-denim',
                'description' => 'Celana jeans denim stretch dengan potongan slim fit',
                'category_id' => 2,
                'price' => 250000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Dress Wanita Midi',
                'slug' => 'dress-wanita-midi',
                'description' => 'Dress midi dengan bahan yang nyaman dan elegan',
                'category_id' => 2,
                'price' => 200000,
                'stock' => 18,
                'status' => 'published',
            ],
            [
                'name' => 'Jaket Levi\'s',
                'slug' => 'jaket-levis',
                'description' => 'Jaket denim original dengan kualitas premium',
                'category_id' => 2,
                'price' => 800000,
                'stock' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Sepatu Nike Air Max',
                'slug' => 'sepatu-nike-air-max',
                'description' => 'Sneakers sporty dengan air cushion technology',
                'category_id' => 2,
                'price' => 1200000,
                'stock' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Tas Backpack Adidas',
                'slug' => 'tas-backpack-adidas',
                'description' => 'Backpack laptop dengan compartment yang luas',
                'category_id' => 2,
                'price' => 450000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Topi Baseball New Era',
                'slug' => 'topi-baseball-new-era',
                'description' => 'Topi baseball dengan adjustable strap',
                'category_id' => 2,
                'price' => 300000,
                'stock' => 25,
                'status' => 'published',
            ],
            [
                'name' => 'Sweater Hoodie',
                'slug' => 'sweater-hoodie',
                'description' => 'Hoodie dengan bahan fleece yang hangat',
                'category_id' => 2,
                'price' => 350000,
                'stock' => 22,
                'status' => 'published',
            ],
            [
                'name' => 'Kaos Polo Ralph Lauren',
                'slug' => 'kaos-polo-ralph-lauren',
                'description' => 'Kaos polo premium dengan embroidered logo',
                'category_id' => 2,
                'price' => 650000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Rok Mini Skirt',
                'slug' => 'rok-mini-skirt',
                'description' => 'Rok mini dengan bahan yang stretchable',
                'category_id' => 2,
                'price' => 180000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Kaos Oblong Lengan Panjang',
                'slug' => 'kaos-oblong-lengan-panjang',
                'description' => 'Kaos katun lengan panjang untuk casual wear',
                'category_id' => 2,
                'price' => 80000,
                'stock' => 30,
                'status' => 'published',
            ],
            [
                'name' => 'Blazer Wanita',
                'slug' => 'blazer-wanita',
                'description' => 'Blazer formal untuk penampilan profesional',
                'category_id' => 2,
                'price' => 750000,
                'stock' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'Sandals Crocs',
                'slug' => 'sandals-crocs',
                'description' => 'Sandal comfort yang nyaman untuk sehari-hari',
                'category_id' => 2,
                'price' => 400000,
                'stock' => 25,
                'status' => 'published',
            ],
            [
                'name' => 'Tank Top Sport',
                'slug' => 'tank-top-sport',
                'description' => 'Tank top untuk olahraga dengan material breathable',
                'category_id' => 2,
                'price' => 120000,
                'stock' => 28,
                'status' => 'published',
            ],
            [
                'name' => 'Cardigan Wanita',
                'slug' => 'cardigan-wanita',
                'description' => 'Cardigan tipis untuk layering outfit',
                'category_id' => 2,
                'price' => 280000,
                'stock' => 18,
                'status' => 'published',
            ],

            // RUMAH TANGGA CATEGORY (ID: 3) - 15 products
            [
                'name' => 'Blender Philips',
                'slug' => 'blender-philips',
                'description' => 'Blender multifungsi dengan 6 pilihan kecepatan',
                'category_id' => 3,
                'price' => 300000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Magic Com Panasonic',
                'slug' => 'magic-com-panasonic',
                'description' => 'Rice cooker 3 liter dengan keep warm function',
                'category_id' => 3,
                'price' => 450000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Kulkas 2 Pintu Sharp',
                'slug' => 'kulkas-2-pintu-sharp',
                'description' => 'Kulkas hemat energi dengan kapasitas 180 liter',
                'category_id' => 3,
                'price' => 3500000,
                'stock' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Mesin Cuci Samsung',
                'slug' => 'mesin-cuci-samsung',
                'description' => 'Mesin cuci front loading 7kg dengan eco bubble',
                'category_id' => 3,
                'price' => 4200000,
                'stock' => 6,
                'status' => 'published',
            ],
            [
                'name' => 'Setrika Philips',
                'slug' => 'setrika-philips',
                'description' => 'Setrika uap dengan soleplate keramik',
                'category_id' => 3,
                'price' => 350000,
                'stock' => 25,
                'status' => 'published',
            ],
            [
                'name' => 'Vacuum Cleaner Dyson',
                'slug' => 'vacuum-cleaner-dyson',
                'description' => 'Cordless vacuum cleaner dengan HEPA filter',
                'category_id' => 3,
                'price' => 5500000,
                'stock' => 5,
                'status' => 'published',
            ],
            [
                'name' => 'Air Purifier Xiaomi',
                'slug' => 'air-purifier-xiaomi',
                'description' => 'Air purifier dengan HEPA filter dan smart control',
                'category_id' => 3,
                'price' => 1200000,
                'stock' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Mixer Philips',
                'slug' => 'mixer-philips',
                'description' => 'Hand mixer dengan 5 speed settings',
                'category_id' => 3,
                'price' => 550000,
                'stock' => 18,
                'status' => 'published',
            ],
            [
                'name' => 'Toaster Oxone',
                'slug' => 'toaster-oxone',
                'description' => 'Toaster 2 slice dengan automatic shutoff',
                'category_id' => 3,
                'price' => 280000,
                'stock' => 20,
                'status' => 'published',
            ],
            [
                'name' => 'Coffee Maker Delonghi',
                'slug' => 'coffee-maker-delonghi',
                'description' => 'Espresso machine untuk kopi profesional di rumah',
                'category_id' => 3,
                'price' => 2800000,
                'stock' => 4,
                'status' => 'published',
            ],
            [
                'name' => 'Microwave Sharp',
                'slug' => 'microwave-sharp',
                'description' => 'Microwave 20 liter dengan auto menu functions',
                'category_id' => 3,
                'price' => 950000,
                'stock' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'Dispenser Miyako',
                'slug' => 'dispenser-miyako',
                'description' => 'Dispenser air panas dan dingin dengan bottom loading',
                'category_id' => 3,
                'price' => 650000,
                'stock' => 15,
                'status' => 'published',
            ],
            [
                'name' => 'Exhaust Fan Panasonic',
                'slug' => 'exhaust-fan-panasonic',
                'description' => 'Exhaust fan untuk dapur dengan low noise',
                'category_id' => 3,
                'price' => 450000,
                'stock' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Lampu LED Philips',
                'slug' => 'lampu-led-philips',
                'description' => 'Bohlam LED hemat energi dengan brightness tinggi',
                'category_id' => 3,
                'price' => 85000,
                'stock' => 50,
                'status' => 'published',
            ],
            [
                'name' => 'Sofa Bed 2 Seater',
                'slug' => 'sofa-bed-2-seater',
                'description' => 'Sofa multifungsi yang bisa diubah menjadi tempat tidur',
                'category_id' => 3,
                'price' => 2500000,
                'stock' => 3,
                'status' => 'published',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}